### PR TITLE
Create README.md

### LINKED ISSUE #1: Add a README
How can I use this?

### PR DESCRIPTION
**Pull request by javathunderman**
It's pretty vague, but it fixes #1.

### CODE REVIEW

**Comment by javathunderman** [comment]
@moollaza Should we merge this? The readme seems a little vague.

**Comment by moollaza** [comment]
Sure. Thanks @javathunderman

**Comment by kentfredric** [comment]
The "Right" way to do it would be document it in `Translate.pm` using POD, and then have an auxilliary process that creates a README from that. But the latter part at present is a bit ugly, so I'm just suggesting "This doc patch should be in 2 places not 1" for the time being.

**Comment by moollaza** [comment]
@kentfredric thanks for letting me know. This Repo doesn't get/need much attention so I think the simple README is fine. You're welcome to make a PR though :)

It's also not a CPAN module, so there aren't many people outside of DDG looking/using this.

**Pull request merged**
